part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const LOGIN = _Paths.LOGIN;
  static const SPLASH = _Paths.SPLASH;
  static const REGISTER = _Paths.REGISTER;
  static const WELCOME = _Paths.WELCOME;
  static const OTP = _Paths.OTP;
  static const LAYOUT_MY = _Paths.LAYOUT_MY;
  static const ABOUT_MY = _Paths.ABOUT_MY;
  static const CHANGE_MOBILE_NO_MY = _Paths.CHANGE_MOBILE_NO_MY;
  static const EDIT_PROFILE_MY = _Paths.EDIT_PROFILE_MY;
  static const CONTACT_MY = _Paths.CONTACT_MY;
  static const TOPUP = _Paths.TOPUP;
  static const WITHDRAW_MY = _Paths.WITHDRAW_MY;
  static const TRANSFER_MY = _Paths.TRANSFER_MY;
  static const TOPUP_MY = _Paths.TOPUP_MY;
  static const RECEIPT_MY = _Paths.RECEIPT_MY;
  static const SPENDING_MY = _Paths.SPENDING_MY;
  static const RECIPIENT_DETAIL_MY = _Paths.RECIPIENT_DETAIL_MY;
  static const WALLET_INFO_MY = _Paths.WALLET_INFO_MY;
  static const REQUEST_MY = _Paths.REQUEST_MY;
  static const REQUEST_MONEY_MY = _Paths.REQUEST_MONEY_MY;
  static const REQUEST_RECEIPT_MY = _Paths.REQUEST_RECEIPT_MY;
  static const KYC_MY = _Paths.KYC_MY;
  static const KYC_RESULT_MY = _Paths.KYC_RESULT_MY;
  static const REGISTER_WALLET_MY = _Paths.REGISTER_WALLET_MY;
  static const REMITTANCE_MY = _Paths.REMITTANCE_MY;
  static const REMITTANCE_FORM_MY = _Paths.REMITTANCE_FORM_MY;
  static const SCAN_TRANSFER_MY = _Paths.SCAN_TRANSFER_MY;
  static const QR_CODE_MY = _Paths.QR_CODE_MY;
  static const WALLET_RESULT_MY = _Paths.WALLET_RESULT_MY;
  static const REGISTER_WALLET_FORM_MY = _Paths.REGISTER_WALLET_FORM_MY;
  static const EXCHANGE_RATE_MY = _Paths.EXCHANGE_RATE_MY;
  static const REMITTANCE_BENEFICIARY_MY = _Paths.REMITTANCE_BENEFICIARY_MY;
  static const CONFIRMATION_REMITTANCE_MY = _Paths.CONFIRMATION_REMITTANCE_MY;
  static const PAYMENT_METHOD_MY = _Paths.PAYMENT_METHOD_MY;
  static const FPX_MY = _Paths.FPX_MY;
  static const REMITTANCE_RECEIPT_MY = _Paths.REMITTANCE_RECEIPT_MY;
  static const BENEFICIARY_INFO_MY = _Paths.BENEFICIARY_INFO_MY;
  static const FORGOT_PASSWORD_MY = _Paths.FORGOT_PASSWORD_MY;
  static const FORGOT_PASSWORD_FORM = _Paths.FORGOT_PASSWORD_FORM;
  static const NATIONALITY = _Paths.NATIONALITY;
  static const MANUAL_KYC = _Paths.MANUAL_KYC;
  static const SENDER_INFORMATION = _Paths.SENDER_INFORMATION;
  static const KYC_IMAGE = _Paths.KYC_IMAGE;
  static const LOGIN_SECOND = _Paths.LOGIN_SECOND;
  static const BILL_PAYMENT = _Paths.BILL_PAYMENT;
  static const PREPAID_TOPUP = _Paths.PREPAID_TOPUP;
  static const PREPAID_TOPUP_FORM = _Paths.PREPAID_TOPUP_FORM;
  static const POSTPAID_TOPUP = _Paths.POSTPAID_TOPUP;
  static const REFERREL_CODE = _Paths.REFERREL_CODE;
  static const REGISTER_FORM = _Paths.REGISTER_FORM;
  static const WALLET_BENEFIT = _Paths.WALLET_BENEFIT;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const SPLASH = '/splash';
  static const REGISTER = '/register';
  static const WELCOME = '/welcome';
  static const OTP = '/otp';
  static const LAYOUT = '/layout';
  static const ABOUT = '/about';
  static const CHANGE_MOBILE_NO = '/change-mobile-no';
  static const PROFILE = '/profile';
  static const EDIT_PROFILE = '/edit-profile';
  static const CONTACT = '/contact';
  static const TOPUP = '/topup';
  static const RECEIPT = '/receipt';
  static const WITHDRAW = '/withdraw';
  static const TRANSFER = '/transfer';
  static const SPENDING = '/spending';
  static const RECIPIENT_DETAIL = '/recipient-detail';
  static const WALLET_INFO = '/wallet-info';
  static const WALLET = '/wallet';
  static const REQUEST = '/request-my';
  static const REQUEST_MONEY = '/request-money-my';
  static const REQUEST_RECEIPT = '/request-receipt-my';
  static const KYC = '/kyc-my';
  static const KYC_RESULT = '/kyc-result-my';
  static const REGISTER_WALLET = '/register-wallet-my';
  static const REMITTANCE = '/remittance-my';
  static const REMITTANCE_FORM = '/remittance-form-my';
  static const SCAN_TRANSFER = '/scan-transfer-my';
  static const QR_CODE = '/qr-code-my';
  static const WALLET_RESULT = '/wallet-result-my';
  static const REGISTER_WALLET_FORM = '/register-wallet-form-my';
  static const EXCHANGE_RATE = '/exchange-rate-my';
  static const REMITTANCE_BENEFICIARY = '/remittance-beneficiary-my';
  static const CONFIRMATION_REMITTANCE = '/confirmation-remittance-my';
  static const PAYMENT_METHOD = '/payment-method-my';
  static const FPX = '/fpx-my';
  static const REMITTANCE_RECEIPT = '/remittance-receipt-my';
  static const BENEFICIARY_INFO = '/beneficiary-info-my';

  // MALAYSIA
  static const MALAYSIA = '/malaysia';
  static const LAYOUT_MY = MALAYSIA + LAYOUT;
  static const ABOUT_MY = MALAYSIA + PROFILE + ABOUT;
  static const CHANGE_MOBILE_NO_MY = MALAYSIA + PROFILE + CHANGE_MOBILE_NO;
  static const EDIT_PROFILE_MY = MALAYSIA + PROFILE + EDIT_PROFILE;
  static const CONTACT_MY = MALAYSIA + PROFILE + CONTACT;
  static const WITHDRAW_MY = MALAYSIA + WITHDRAW;
  static const TRANSFER_MY = MALAYSIA + TRANSFER;
  static const TOPUP_MY = MALAYSIA + TOPUP;
  static const RECEIPT_MY = MALAYSIA + RECEIPT;
  static const SPENDING_MY = MALAYSIA + SPENDING;
  static const RECIPIENT_DETAIL_MY = MALAYSIA + RECIPIENT_DETAIL;
  static const WALLET_INFO_MY = MALAYSIA + WALLET + WALLET_INFO;
  static const REQUEST_MY = MALAYSIA + REQUEST;
  static const REQUEST_MONEY_MY = MALAYSIA + REQUEST + REQUEST_MONEY;
  static const REQUEST_RECEIPT_MY = MALAYSIA + REQUEST + REQUEST_MONEY_MY;
  static const KYC_MY = MALAYSIA + KYC;
  static const KYC_RESULT_MY = MALAYSIA + KYC + KYC_RESULT;
  static const REGISTER_WALLET_MY = MALAYSIA + REGISTER_WALLET;
  static const REMITTANCE_MY = MALAYSIA + REMITTANCE;
  static const REMITTANCE_FORM_MY = MALAYSIA + REMITTANCE + REMITTANCE_FORM;
  static const SCAN_TRANSFER_MY = MALAYSIA + TRANSFER + SCAN_TRANSFER;
  static const QR_CODE_MY = MALAYSIA + SPENDING + QR_CODE;
  static const WALLET_RESULT_MY = MALAYSIA + REGISTER_WALLET + WALLET_RESULT;
  static const REGISTER_WALLET_FORM_MY =
      MALAYSIA + REGISTER_WALLET + REGISTER_WALLET_FORM;
  static const EXCHANGE_RATE_MY = MALAYSIA + REMITTANCE + EXCHANGE_RATE;
  static const REMITTANCE_BENEFICIARY_MY =
      MALAYSIA + REMITTANCE + REMITTANCE_BENEFICIARY;
  static const CONFIRMATION_REMITTANCE_MY =
      MALAYSIA + REMITTANCE + CONFIRMATION_REMITTANCE;
  static const PAYMENT_METHOD_MY = MALAYSIA + REMITTANCE + PAYMENT_METHOD;
  static const FPX_MY = MALAYSIA + FPX;
  static const REMITTANCE_RECEIPT_MY =
      MALAYSIA + REMITTANCE + REMITTANCE_RECEIPT;
  static const BENEFICIARY_INFO_MY = MALAYSIA + REMITTANCE + BENEFICIARY_INFO;
  static const FORGOT_PASSWORD_MY = '/forgot-password-my';
  static const FORGOT_PASSWORD_FORM = '/forgot-password-form';
  static const NATIONALITY = '/nationality';
  static const MANUAL_KYC = '/manual-kyc';
  static const SENDER_INFORMATION = '/sender-information';
  static const KYC_IMAGE = '/kyc-image';
  static const LOGIN_SECOND = '/login-second';
  static const BILL_PAYMENT = '/bill-payment';
  static const PREPAID_TOPUP = '/prepaid-topup';
  static const PREPAID_TOPUP_FORM = '/prepaid-topup-form';
  static const POSTPAID_TOPUP = '/postpaid-topup';
  static const REFERREL_CODE = '/referrel-code';
  static const REGISTER_FORM = '/register-form';
  static const WALLET_BENEFIT = '/wallet-benefit';
}
